export const badges= [
    { id: 1, name: 'Runner', detail:'Run 10 kilometers in 1 day',img:'/assets/badge1.png' },
    { id: 2, name: 'Cyclist', detail:'Cycle 15 kilometers in a day',img:'/assets/badge2.png' },
    { id: 3, name: 'King of the Hill', detail:'Be on top of the leaderboard chart for 1 week straight',img:'/assets/badge3.png' },
    { id: 4, name: 'Healthy Heart', detail:'Creating a habit takes 28 days. Make fitness one',img:'/assets/badge4.png'},
    { id: 5, name: 'Yogi', detail:'Stretch your body doing yoga for one week straight',img:'/assets/badge5.png' },
    { id: 6, name: 'Fat burner', detail:'Lose more than 5 kgs in a month',img:'/assets/badge6.png' },
    { id: 7, name: 'In a Flash', detail:'Run 5 kilometers in 25 minutes',img:'/assets/badge7.png' },
    { id: 8, name: 'Shredder', detail:'Lose fat. Gain Muscles. Show them off',img:'/assets/badge8.png' },
    { id: 9, name: 'Pro Runner', detail:'Run 21.1 kilometers in a day',img:'/assets/badge10.png' },
    { id: 10, name: 'Marathon Runner', detail:'Run 21.1 kilometers in a day',img:'/assets/badge9.png' },
    { id: 11, name: 'Healthy Eating', detail:'Purchase protein shakes and gain some muscles',img:'/assets/badge11.png' },
    { id: 12, name: 'Fitness Freak', detail:'Keep a 50 day streak',img:'/assets/badge12.png' },
    { id: 13, name: 'Friendly Feud', detail:'Invite 5 firends and compete with them',img:'/assets/badge13.png' },
    { id: 14, name: 'Replenished', detail:'Earn an energy drink coupon and replenish your vitamins',img:'/assets/badge14.png' },
    { id: 15, name: 'Weight Dropper', detail:'Lose weight consistently for 2 months',img:'/assets/badge15.png' },
    { id: 16, name: 'Make it Rain', detail:'Plant 50 trees',img:'/assets/badge16.png' },
    { id: 17, name: 'Badge 17', detail:'About',img:'/assets/badge17.png' },
    { id: 18, name: 'Badge 18', detail:'About',img:'/assets/badge18.png' },
    { id: 19, name: 'Secure Dispose', detail:'Dispose e-waste securely 5 times',img:'/assets/badge19.png' },
    { id: 20, name: 'The Farmer in You', detail:'Plant 10 trees',img:'/assets/badge20.png' },
    { id: 21, name: 'e-Commute', detail:'Travel in any commute 50 times',img:'/assets/badge21.png' },
    { id: 22, name: 'jhjh', detail:'About',img:'/assets/badge22.png' },
    { id: 23, name: 'Clean energy', detail:'About',img:'/assets/badge23.png' },
    { id: 24, name: 'Hands Together', detail:'Invite 5 friends to volunteer',img:'/assets/badge24.png' },
    { id: 25, name: 'Saviour Salmon', detail:'Spend a weekend in an old age home and help the elderly',img:'/assets/badge25.png' },
    { id: 26, name: 'Educator', detail:'Volunteer to get children educated',img:'/assets/badge26.png' },
    { id: 27, name: 'Out of the World', detail:'Volunteer in all the categories and become an outstanding super contributor',img:'/assets/badge27.png' },
    { id: 28, name: 'Shutter King', detail:'Upload photos in all categories and beacome an all rounder photographer',img:'/assets/badge28.png' },
    { id: 29, name: 'Drone Specialist', detail:'Shots from up the high. Capture the beauty from the sky',img:'/assets/badge29.png' },
    { id: 30, name: 'Time For Print', detail:'Your image is selected as the best of the week and get it featured.',img:'/assets/badge30.png' }
  ];